### ISSUE TITLE
React Compatibility?

### ISSUE THREAD

**Issue by petertait** [mzdr/fluffy.js#1]
This more of a feature request, so feel free to close this as an issue!

But, I've been trying to get this to work with React but it's proving difficult. I think partly because the script loads on dom load rather than on each component mount. This results in the gallery working the first time it loads but fails when returning. Having the repo on NPM would also be of great help for building with webpack/browserify.

ps. Thanks for the great work!

**Comment by mzdr** [comment]
Hey Peter!

Thanks for the feature request! I will look into it as I already had some people notifying me about the troubles when using it in connection with AJAX. I think I will do some slight refactoring so that you can either import/require it or it will automatically initialize itself when it finds any DOM elements. About the NPM part: 

https://www.npmjs.com/package/fluffy.js

I know it's not in the docs, will fix that too asap.

**Comment by petertait** [comment]
Thanks I look forward to your future releases and can't believe I missed the NPM package!

**Comment by mzdr** [comment]
Fixed with 42481fdfa25891904b670e4e7e4768c224fd447e

**Comment by mzdr** [comment]
Alright @petertait, I just released [v2.1.0](https://github.com/mzdr/fluffy.js/releases/tag/v2.1.0). Give it a try and tell me if this fixes your problems with React!

**Comment by petertait** [comment]
Thanks @mzdr for your help, it works like a dream!
